// ── Project page content for each clickable object ──

export const PROJECTS = {
  gillette: {
    title: 'Gillette Venus',
    tag: 'Campaign',
    hero: 'Campaign Visuals',
    description: `A fresh take on the Gillette Venus brand, targeting Gen Z women with bold visuals and unapologetic confidence. We reimagined the shaving ritual as a moment of self-expression — not a chore.`,
    details: `The campaign spans social media, OOH, and digital activations. Every touchpoint celebrates the ritual of getting ready, transforming bathrooms into stages of self-care.`,
    credits: { 'Art Direction': 'Naomi', 'Copywriting': 'Jana', 'Brief': 'Advertising Internship Portfolio' },
  },
  kerastase: {
    title: 'Kerastase',
    tag: 'Campaign',
    hero: 'Campaign Visuals',
    description: `Luxury haircare reimagined for the digital age. We created a campaign that positions Kerastase as the bridge between salon expertise and everyday confidence.`,
    details: `Blending editorial beauty photography with playful Y2K-inspired graphics, the campaign speaks to young professionals who see haircare as an extension of their personal brand.`,
    credits: { 'Art Direction': 'Naomi', 'Copywriting': 'Jana', 'Brief': 'Advertising Internship Portfolio' },
  },
  nike: {
    title: 'Nike',
    tag: 'Campaign Concept',
    hero: 'Campaign Visuals',
    description: `A speculative campaign concept for Nike Women, celebrating movement in all forms — from dance to daily commutes. "Every Step Is a Statement."`,
    details: `We explored how Nike can own the intersection of fashion and function, creating a visual language that speaks to women who move through the city with intention.`,
    credits: { 'Art Direction': 'Naomi', 'Copywriting': 'Jana', 'Brief': 'Speculative Brief' },
  },
  cocacola: {
    title: 'Coca-Cola',
    tag: 'Campaign Concept',
    hero: 'Campaign Visuals',
    description: `A summer activation concept for Coca-Cola — turning living rooms into gathering spaces. "Share the Moment" celebrates the small rituals of togetherness.`,
    details: `From Spotify playlists to limited-edition packaging, the campaign creates a world where every sip is a shared experience.`,
    credits: { 'Art Direction': 'Naomi', 'Copywriting': 'Jana', 'Brief': 'Speculative Brief' },
  },
  fragrance: {
    title: 'Fragrance Brief',
    tag: 'Campaign Concept',
    hero: 'Campaign Visuals',
    description: `A conceptual fragrance campaign exploring the relationship between scent and memory. Each visual tells a story of a moment you want to bottle.`,
    details: `The campaign uses dreamlike imagery and poetic copy to create an emotional connection between the audience and an unnamed luxury fragrance brand.`,
    credits: { 'Art Direction': 'Naomi', 'Copywriting': 'Jana', 'Brief': 'Speculative Brief' },
  },
  aperol: {
    title: 'Aperol Spritz',
    tag: 'Campaign Concept',
    hero: 'Campaign Visuals',
    description: `A sun-soaked activation concept for Aperol — transforming rooftops and balconies into instant vacation moments. "Sunset in a Glass."`,
    details: `The campaign pairs golden-hour aesthetics with cheeky copy, positioning Aperol as the unofficial drink of main-character energy.`,
    credits: { 'Art Direction': 'Naomi', 'Copywriting': 'Jana', 'Brief': 'Speculative Brief' },
  },
  artdirection: {
    title: 'Art Direction',
    tag: 'Portfolio',
    hero: 'Selected Works',
    description: `A collection of art direction work spanning editorial, branding, and digital. Every piece is designed to stop the scroll and start a conversation.`,
    details: `From mood boards to final execution, this collection showcases the visual thinking behind our campaigns.`,
    credits: { 'Art Direction': 'Naomi', 'Curation': 'Jana & Naomi' },
  },
  about: {
    title: 'About Us',
    tag: 'Naomi & Jana',
    hero: null,
    description: `We're Naomi and Jana — an art director and copywriter duo studying advertising. We believe great work comes from genuine curiosity, bold ideas, and not taking ourselves too seriously.`,
    details: `This portfolio is our Dreamhouse — a space that reflects how we think, create, and collaborate. Each room tells a story about our work and who we are. Thanks for exploring.`,
    credits: { 'Art Direction': 'Naomi', 'Copywriting': 'Jana', 'Website': 'Built with love & Three.js' },
  },
  cv: {
    title: 'Our CV',
    tag: 'Experience',
    hero: null,
    description: `Between us, we bring art direction, copywriting, branding, social media strategy, and a relentless drive to create work that matters.`,
    details: `We're currently seeking advertising internships where we can bring our energy, creativity, and collaborative spirit to a team that values bold thinking.`,
    credits: { 'Contact': 'naomi.jana@email.com', 'Location': 'Available for internships' },
  },
};
